#!/bin/bash

# Function to display subdomain information
display_info() {
    local sub_domain=$1
    local domain=$2

    # Perform DNS query and filter relevant information using awk
    dig_output=$(dig $sub_domain.$domain | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$dig_output" | awk '/IN\s/{print $4}')
    destination=$(echo "$dig_output" | awk '/IN\s/{getline; print $1}')

    # Display information
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Main script

# Check if the number of arguments is correct
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1
subdomains=("www" "lb-01" "web-01" "web-02")

# Display information for specified subdomain or default subdomains
if [ "$#" -eq 2 ]; then
    sub_domain=$2
    display_info $sub_domain $domain
else
    for sub_domain in "${subdomains[@]}"; do
        display_info $sub_domain $domain
    done
fi
